### ISSUE TITLE
Backlog

### ISSUE THREAD

**Issue by alexandre-mbm** [alexandre-mbm/slax#1]
- [ ] https://github.com/Tomas-M/linux-live/issues/30 - I want my Slax
- [x] https://github.com/Tomas-M/linux-live/issues/31 - How to copy/paste from/to xterm?
- [x] https://github.com/Tomas-M/linux-live/issues/32 - How to change the language?
- [ ] https://github.com/Tomas-M/linux-live/issues/33 - Ideas for Slax
- [x] https://github.com/Tomas-M/xlunch/issues/74 - Translating (see [xlunch.org](http://xlunch.org/))
- [ ] https://github.com/Tomas-M/android-slax-installer/issues/1 - How it works?
- [ ] [github.com/Qalculate](https://github.com/Qalculate) - _to translate, [see more](https://sourceforge.net/p/qalculate/discussion/296943/thread/f4444f0d/)_

---

[Google Translate](https://translate.google.com/?hl=pt-BR&tab=TT)

**Comment by alexandre-mbm** [comment]
- [ ] Extrair issues em projetos ou milestones neste projeto

**Comment by alexandre-mbm** [comment]
Para fazer alterações nos arquivos .sb eu posso usar algo como:
```sh
apt-get download nomedopacote
dpkg-deb -x nomedopacote ok
cd ok
tar czvf nomedopacote.tar.gz arquivodetradução
unquashfs arquivo.sb
cd diretorio
mksquashfs diretorio arquivo.sb
```

**Comment by alexandre-mbm** [comment]
Informações que talvez venham a ser úteis para resolver atraso na atualização da hora:
- `hwclock -w`
  - [How to set current time on Linux?](https://superuser.com/questions/302396/how-to-set-current-time-on-linux)
- [Set Time, Date Timezone in Linux from Command Line or Gnome | **Use ntp**](https://www.garron.me/en/linux/set-time-date-timezone-ntp-linux-shell-gnome-command-line.html)

---

- [ ] Colocar isso no _startup_ do Fluxbox

**Comment by alexandre-mbm** [comment]
- [x] https://github.com/Tomas-M/linux-live/issues/34 - No sound with snd-hda-intel
- [ ] [linux-live/Slax/debian/modules/05-chromium](https://github.com/Tomas-M/linux-live/tree/master/Slax/debian/modules/05-chromium)
- [ ] [Wifi in Slax](https://www.slax.org/en/blog/24312-Wifi-in-Slax.html)

**Comment by alexandre-mbm** [comment]
Arquivos de boot e build:
- [ ] [linux-live/Slax](https://github.com/Tomas-M/linux-live/tree/master/Slax)

**Comment by alexandre-mbm** [comment]
- [ ] [textadept](https://foicica.com/textadept/)
